version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg-volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
